apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: combiner-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: combiner-{{ .Values.nameSuffix }}
spec:
  selector:
    matchLabels:
      name: combiner-{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        name: combiner-{{ .Values.nameSuffix }}
    spec:
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      imagePullSecrets:
      - name: docker-hub-zhenghengli
      containers:
      - name: combiner
        image: zhenghengli/diffraflow:latest
        command:
        - combiner
        - --config=/config/combiner.conf
        - --logconf=/config/log4cxx.properties
        ports:
        - containerPort: {{ .Values.imgfrmListenPort }}
          hostPort: {{ .Values.imgfrmListenPort }}
        - containerPort: {{ .Values.imgdatListenPort }}
          hostPort: {{ .Values.imgdatListenPort }}
        - containerPort: {{ .Values.httpListenPort }}
          hostPort: {{ .Values.httpListenPort }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
      nodeSelector:
        diffraflow/node-type: daq-ana
      volumes:
      - name: config-volume
        configMap:
          name: combiner-config-{{ .Values.nameSuffix }}
