apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: combiner-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: combiner-{{ .Values.nameSuffix }}
spec:
  selector:
    matchLabels:
      name: combiner-{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        name: combiner-{{ .Values.nameSuffix }}
    spec:
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      # imagePullSecrets:
      #   - name: docker-hub-zhenghengli
      containers:
        - name: combiner
          # image: zhenghengli/diffraflow:latest
          image: 10.15.86.19:25443/diffraflow:latest
          command:
            - taskset
            - --cpu-list
            - 0-23
            - combiner
            - --config=/config/combiner.conf
            - --logconf=/config/log4cxx.properties
          ports:
            - containerPort: {{.Values.imgfrmListenPort}}
              hostPort: {{.Values.imgfrmListenPort}}
            - containerPort: {{.Values.imgdatListenPort}}
              hostPort: {{.Values.imgdatListenPort}}
            - containerPort: {{.Values.httpListenPort}}
              hostPort: {{.Values.httpListenPort}}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: sock-volume
              mountPath: /sock
      nodeSelector:
        diffraflow/node-type: daq-ana
      volumes:
        - name: config-volume
          configMap:
            name: combiner-config-{{ .Values.nameSuffix }}
        - name: sock-volume
          hostPath:
            path: /kubernetes/data/lizhh1/diffraflow/run
