apiVersion: batch/v1
kind: Job
metadata:
  name: alignment-index-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: alignment-index-{{ .Values.nameSuffix }}
spec:
  template:
    metadata:
      labels:
        name: alignment-index-{{ .Values.nameSuffix }}
    spec:
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      imagePullSecrets:
      - name: docker-hub-zhenghengli
      containers:
      - name: alignment-index
        image: zhenghengli/diffraflow:latest
        command:
        - alignment_index_proc.py
        - -s 6
        - /input-data
        - /aux-files/alignment-index-r0243_0-5.h5
        volumeMounts:
        - name: input-data
          mountPath: /input-data
        - name: aux-files
          mountPath: /aux-files
      volumes:
      - name: input-data
        hostPath:
          path: /data-ib/home/lizhh1/data/CXIDB/id83/r0243/proc
      - name: aux-files
        hostPath:
          path: /data-ib/home/lizhh1/data/CXIDB/id83/r0243-conv/aux-files
      restartPolicy: Never
