apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingester-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: ingester-{{ .Values.nameSuffix }}
spec:
  selector:
    matchLabels:
      name: ingester-{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        name: ingester-{{ .Values.nameSuffix }}
    spec:
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      # imagePullSecrets:
      #   - name: docker-hub-zhenghengli
      containers:
        - name: ingester
          # image: zhenghengli/diffraflow:latest
          image: 10.15.86.19:25443/diffraflow:latest
          command:
            - taskset
            - --cpu-list
            - 0-23
            - ingester
            - --config=/config/ingester.conf
            - --logconf=/config/log4cxx.properties
          ports:
            - containerPort: {{.Values.imageHttpPort}}
              hostPort: {{.Values.imageHttpPort}}
            - containerPort: {{.Values.metricsHttpPort}}
              hostPort: {{.Values.metricsHttpPort}}
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CUDA_MPS_PIPE_DIRECTORY
              value: /nvidia/mps
            - name: CUDA_MPS_LOG_DIRECTORY
              value: /nvidia/log
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: sock-volume
              mountPath: /sock
            - name: ingester-data
              mountPath: /ingester-data
            - name: calib-data
              mountPath: /calib-data
            - name: cuda-mps-pipe
              mountPath: /nvidia/mps
            - name: cuda-mps-log
              mountPath: /nvidia/log
            - name: dev-shm
              mountPath: /dev/shm
      nodeSelector:
        diffraflow/node-type: daq-ana
      volumes:
        - name: config-volume
          configMap:
            name: ingester-config-{{ .Values.nameSuffix }}
        - name: sock-volume
          hostPath:
            path: /kubernetes/data/lizhh1/diffraflow/run
        - name: ingester-data
          hostPath:
            path: /data-ib/home/lizhh1/diffraflow/ingester
        - name: calib-data
          hostPath:
            path: /data-ib/home/lizhh1/data/CXIDB/id83/r0243-conv/aux-files
        - name: cuda-mps-pipe
          hostPath:
            path: /kubernetes/data/lizhh1/nvidia/mps
        - name: cuda-mps-log
          hostPath:
            path: /kubernetes/data/lizhh1/nvidia/log
        - name: dev-shm
          hostPath:
            path: /dev/shm
