apiVersion: v1
kind: ConfigMap
metadata:
  name: ingester-config-{{ .Values.nameSuffix }}
  namespace: diffraflow
data:
  ingester.conf: |
    ## zookeeper settings
    zookeeper_server = zookeeper:2181
    zookeeper_chroot = /diffraflow
    zookeeper_expiration_time = 10000
    zookeeper_log_level = warn
    zookeeper_config_path = /ingester.dyconf

    ## static parameters
    ingester_id = {{ .Values.ingesterID }}
    # combiner_host = NODE_IP
    # combiner_port = {{ .Values.combinerPort }}
    combiner_sock = /sock/{{ .Values.combinerSock }}
    image_http_host = 0.0.0.0
    image_http_port = {{ .Values.imageHttpPort }}
    recnxn_wait_time = 1000
    recnxn_max_count = 5
    imgdat_queue_capacity = 100

    # storage_dir = /ingester-data
    hdf5_chunk_size = 10
    hdf5_buffer_size = 10
    hdf5_compress_level = 3
    hdf5_swmr_mode = true
    file_imgcnt_limit = 3

    ## dynamic parameters
    dy_run_number = 0
    dy_param_int = 20
    dy_param_double = 4.567
    dy_param_string = xfel

    ## metrics http server
    metrics_http_host = 0.0.0.0
    metrics_http_port = {{ .Values.metricsHttpPort }}

    ## metrics pulsar setting
    metrics_pulsar_broker_address = pulsar://pulsar-broker:6650
    metrics_pulsar_topic_name = persistent://zhenghengli/diffraflow/ingester
    metrics_pulsar_message_key = ingester-{{ .Values.nameSuffix }}@NODE_NAME
    metrics_pulsar_report_period = 1000

  log4cxx.properties: |
    log4j.rootLogger = WARN, Console
    log4j.appender.Console = org.apache.log4j.ConsoleAppender
    log4j.appender.Console.layout = org.apache.log4j.PatternLayout
    log4j.appender.Console.layout.ConversionPattern= %d [%t] %-5p %c - %m%n
