apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aggregator-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: aggregator-{{ .Values.nameSuffix }}
spec:
  selector:
    matchLabels:
      name: aggregator-{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        name: aggregator-{{ .Values.nameSuffix }}
    spec:
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      # imagePullSecrets:
      #   - name: docker-hub-zhenghengli
      containers:
        - name: aggregator
          # image: zhenghengli/diffraflow:latest
          image: 10.15.86.19:25443/diffraflow:latest
          command:
            - aggregator
            - --config=/config/aggregator.conf
            - --logconf=/config/log4cxx.properties
          ports:
            - containerPort: {{.Values.httpPort}}
              hostPort: {{.Values.httpPort}}
            - containerPort: {{.Values.metricsHttpPort}}
              hostPort: {{.Values.metricsHttpPort}}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: /config
      nodeSelector:
        kubernetes.io/hostname: kube-worker-2
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      volumes:
        - name: config-volume
          configMap:
            name: aggregator-config-{{ .Values.nameSuffix }}
