apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: diffraflow
data:
  zoo.cfg: |
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=100
    standaloneEnabled=false
    admin.enableServer=true
    clientPort=2181
    server.1=kube-worker-1:2888:3888
    server.2=kube-worker-2:2888:3888
    server.3=kube-worker-3:2888:3888
    quorumListenOnAllIPs=true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zookeeper
  namespace: diffraflow
  labels:
    k8s-app: zookeeper
spec:
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.5.7
        command:
        - sh
        - -c
        - >-
          chown -R 42700:42700 /data /datalog /logs &&
          chown 42700:42700 /conf &&
          gosu 42700:42700 zkServer.sh start-foreground
        ports:
        - name: client
          containerPort: 2181
          hostPort: 2181
        - name: server
          containerPort: 2888
          hostPort: 2888
        - name: leader-election
          containerPort: 3888
          hostPort: 3888
        - name: admin-server
          containerPort: 8080
          hostPort: 2180
        volumeMounts:
        - name: zk-data
          mountPath: "/data"
        - name: zk-data-log
          mountPath: "/datalog"
        - name: zk-logs
          mountPath: "/logs"
        - name: zk-config
          subPath: "zoo.cfg"
          mountPath: "/conf/zoo.cfg"
      nodeSelector:
        diffraflow/zookeeper: present
      volumes:
      - name: zk-data
        hostPath:
          path: "/data/zookeeper/data"
      - name: zk-data-log
        hostPath:
          path: "/data/zookeeper/dataLog"
      - name: zk-logs
        hostPath:
          path: "/data/zookeeper/logs"
      - name: zk-config
        configMap:
          name: zookeeper-config
