#!/bin/bash
echo "Start time: $(date)"
docker build --build-arg SOURCE_COMMIT="$SOURCE_COMMIT" --build-arg COMMIT_MSG="$COMMIT_MSG" --build-arg BUILD_TIME="$(date)" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
echo "Finish time: $(date)"
