#!/bin/bash
# debug
echo $SHELL
echo $BASH_VERSION
printf "[$COMMIT_MSG]"
val1="${COMMIT_MSG%'\n'}"
printf "[$val1]"
val2="${COMMIT_MSG%%*('\n')}"
printf "[$val2]"
docker build --build-arg SOURCE_COMMIT="$SOURCE_COMMIT" --build-arg COMMIT_MSG="$val2" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
echo "done"
