apiVersion: batch/v1
kind: Job
metadata:
  name: generator-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: generator-{{ .Values.nameSuffix }}
spec:
  template:
    metadata:
      labels:
        name: generator-{{ .Values.nameSuffix }}
    spec:
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      imagePullSecrets:
        - name: gitlab-registry-lizhengheng
      containers:
        - name: generator
          # image: 10.15.86.19:25443/diffraflow:latest
          image: registry.physky.org/lizhengheng/diffraflow:latest
          command:
            - generator
            - --datdir=/input-data
            - --modid={{ .Values.moduleID }}
            - --outdir=/converted
            - --calib=/aux-files/calib-rand-s0.h5
            - --align=/aux-files/alignment-index-r0243_0-5.h5
            - --event=/aux-files/event-num-r0243_0-5.h5
            - --maxevt=10000
          volumeMounts:
            - name: input-data
              mountPath: /input-data
            - name: aux-files
              mountPath: /aux-files
            - name: converted
              mountPath: /converted
      volumes:
        - name: input-data
          hostPath:
            path: /data-ib/home/lizhh1/data/CXIDB/id83/r0243/proc
        - name: aux-files
          hostPath:
            path: /data-ib/home/lizhh1/data/CXIDB/id83/r0243-conv/aux-files
        - name: converted
          hostPath:
            path: /data-ib/home/lizhh1/data/CXIDB/id83/r0243-conv/converted
      restartPolicy: Never
