apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: combiner-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: combiner-{{ .Values.nameSuffix }}
spec:
  selector:
    matchLabels:
      name: combiner-{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        name: combiner-{{ .Values.nameSuffix }}
    spec:
      imagePullSecrets:
      - name: docker-hub
      containers:
      - name: combiner
        image: zhenghengli/diffraflow:latest
        command:
        - combiner
        - --config=/config/combiner.conf
        - --logconf=/config/log4cxx.properties
        ports:
        - containerPort: {{ .Values.listenPort }}
          hostPort: {{ .Values.listenPort }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
      nodeSelector:
        diffraflow/node-type: daq-ana
      volumes:
      - name: config-volume
        configMap:
          name: combiner-config-{{ .Values.nameSuffix }}
