apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dispatcher-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: dispatcher-{{ .Values.nameSuffix }}
spec:
  selector:
    matchLabels:
      name: dispatcher-{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        name: dispatcher-{{ .Values.nameSuffix }}
    spec:
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      imagePullSecrets:
        - name: docker-hub-zhenghengli
      initContainers:
        - name: combiner-cnxn-checker
          image: zhenghengli/diffraflow:latest
          command:
            - check_cnxn_addrlist.sh
            - /config/combiner_addresses.txt
          volumeMounts:
            - name: config-volume
              mountPath: /config
      containers:
        - name: dispatcher
          image: zhenghengli/diffraflow:latest
          command:
            - dispatcher
            - --config=/config/dispatcher.conf
            - --cmbaddr=/config/combiner_addresses.txt
            - --logconf=/config/log4cxx.properties
          ports:
            - containerPort: {{.Values.listenPort}}
              hostPort: {{.Values.listenPort}}
            - containerPort: {{.Values.httpListenPort}}
              hostPort: {{.Values.httpListenPort}}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: /config
      nodeSelector:
        diffraflow/node-type: daq-ana
      volumes:
        - name: config-volume
          configMap:
            name: dispatcher-config-{{ .Values.nameSuffix }}
