apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sender-{{ .Values.nameSuffix }}
  namespace: diffraflow
  labels:
    k8s-app: sender-{{ .Values.nameSuffix }}
spec:
  selector:
    matchLabels:
      name: sender-{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        name: sender-{{ .Values.nameSuffix }}
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      imagePullSecrets:
        - name: gitlab-registry-lizhengheng
      containers:
        - name: sender
          # image: 10.15.86.19:25443/diffraflow:latest
          image: registry.physky.org/lizhengheng/diffraflow:latest
          command:
            - sender
            - --config=/config/sender.conf
            - --nodemap=/config/node_map.txt
            - --logconf=/config/log4cxx.properties
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: raw-data
              mountPath: /raw-data
      nodeSelector:
        diffraflow/node-type: service
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      volumes:
        - name: config-volume
          configMap:
            name: sender-config-{{ .Values.nameSuffix }}
        - name: raw-data
          hostPath:
            path: {{.Values.rawDataDir}}
