/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>


#include "Configuration.hpp"
#include "ImageFrame.hpp"

#include "BlockingQueue.hpp"

using namespace std;
using namespace shine;

int main(int argc, char** argv) {

    if (argc < 3) {
        cout << "Usage: " << "ingester" << " <topic> <config.conf>" << endl;
        return 2;
    }

    string topic = argv[1];
    string config_fn = argv[2];
    shine::Configuration config;
    if (!config.load(config_fn.c_str())) {
        cout << "Failed to load configuration file: " << config_fn << endl;
        return 1;
    }

    cout << endl;
    config.print();
    cout << endl;
    cout << " The topic to consume: " << topic << endl;
    cout << endl;


    return 0;
}
