apiVersion: v1
kind: Service
metadata:
  name: bookkeeper
  namespace: diffraflow
  labels:
    k8s-app: bookkeeper
spec:
  clusterIP: None
  selector:
    name: bookkeeper
  ports:
  - name: bookie
    port: 3181
  - name: http-server
    port: 3180
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bookkeeper
  namespace: diffraflow
  labels:
    k8s-app: bookkeeper
spec:
  selector:
    matchLabels:
      name: bookkeeper
  template:
    metadata:
      labels:
        name: bookkeeper
    spec:
      nodeSelector:
        diffraflow/node-type: service
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: bookkeeper-data-journal
        hostPath:
          path: "/data/bookkeeper/dataJournal"
      - name: bookkeeper-data-ledger
        hostPath:
          path: "/data/bookkeeper/dataLedger"
      - name: bookkeeper-logs
        hostPath:
          path: "/data/bookkeeper/logs"
      securityContext:
        runAsUser: 42700
        runAsGroup: 42700
        fsGroup: 42700
      containers:
      - name: bookkeeper
        image: zhenghengli/bookkeeper:4.9.2
        imagePullPolicy: Always
        args:
        - bookkeeper
        - bookie
        env:
        - name: BOOKIE_ADVERTISE_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZK_SERVERS
          value: "kube-worker-1:2181;kube-worker-2:2181;kube-worker-3:2181"
        - name: ZK_CHROOT
          value: "bookkeeper"
        volumeMounts:
        - name: bookkeeper-data-journal
          mountPath: "/bookkeeper/dataJournal"
        - name: bookkeeper-data-ledger
          mountPath: "/bookkeeper/dataLedger"
        - name: bookkeeper-logs
          mountPath: "/bookkeeper/logs"
        ports:
        - name: bookie
          containerPort: 3181
          hostPort: 3181
        - name: http-server
          containerPort: 3180
          hostPort: 3180
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bookkeeper-autorecovery
  namespace: diffraflow
  labels:
    k8s-app: bookkeeper
spec:
  replicas: 2
  selector:
    matchLabels:
      name: bookkeeper-autorecovery
  template:
    metadata:
      labels:
        name: bookkeeper-autorecovery
    spec:
      nodeSelector:
        diffraflow/node-type: service
      volumes:
      - name: bookkeeper-logs
        hostPath:
          path: "/data/bookkeeper/logs"
      securityContext:
        runAsUser: 42700
        runAsGroup: 42700
        fsGroup: 42700
      containers:
      - name: bookkeeper
        image: zhenghengli/bookkeeper:4.9.2
        imagePullPolicy: Always
        args:
        - bookkeeper
        - autorecovery
        env:
        - name: ZK_SERVERS
          value: "kube-worker-1:2181;kube-worker-2:2181;kube-worker-3:2181"
        - name: ZK_CHROOT
          value: "bookkeeper"
        volumeMounts:
        - name: bookkeeper-logs
          mountPath: "/bookkeeper/logs"
