apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-mps
  namespace: diffraflow
  labels:
    k8s-app: nvidia-mps
spec:
  selector:
    matchLabels:
      name: nvidia-mps
  template:
    metadata:
      labels:
        name: nvidia-mps
    spec:
      nodeSelector:
        diffraflow/node-type: daq-ana
      volumes:
        - name: cuda-mps-pipe
          hostPath:
            path: /kubernetes/data/lizhh1/nvidia/mps
        - name: cuda-mps-log
          hostPath:
            path: /kubernetes/data/lizhh1/nvidia/log
        - name: dev-shm
          hostPath:
            path: /dev/shm
      securityContext:
        runAsUser: 1017
        runAsGroup: 1010
      imagePullSecrets:
        - name: gitlab-registry-lizhengheng
      containers:
        - name: nvidia-cuda-mps-control
          # image: 10.15.86.19:25443/diffraflow:latest
          image: registry.physky.org/lizhengheng/diffraflow:latest
          command:
            - nvidia-cuda-mps-control
            - -f
          env:
            - name: CUDA_MPS_PIPE_DIRECTORY
              value: /nvidia/mps
            - name: CUDA_MPS_LOG_DIRECTORY
              value: /nvidia/log
          volumeMounts:
            - name: cuda-mps-pipe
              mountPath: /nvidia/mps
            - name: cuda-mps-log
              mountPath: /nvidia/log
            - name: dev-shm
              mountPath: /dev/shm
