apiVersion: v1
kind: Service
metadata:
  name: pulsar-broker
  namespace: diffraflow
  labels:
    k8s-app: pulsar-broker
spec:
  clusterIP: None
  selector:
    name: pulsar-broker
  ports:
  - name: broker-service
    port: 6650
  - name: web-service
    port: 6680
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pulsar-broker
  namespace: diffraflow
  labels:
    k8s-app: pulsar-broker
spec:
  selector:
    matchLabels:
      name: pulsar-broker
  template:
    metadata:
      labels:
        name: pulsar-broker
    spec:
      nodeSelector:
        diffraflow/node-type: service
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: broker-logs
        hostPath:
          path: "/data/pulsar/psLogs"
      securityContext:
        runAsUser: 42700
        runAsGroup: 42700
        fsGroup: 42700
      containers:
      - name: pulsar-broker
        image: zhenghengli/pulsar:2.5.0
        imagePullPolicy: Always
        args:
        - pulsar
        - broker
        env:
        - name: PULSAR_CLUSTER_NAME
          value: pulsar-cluster
        - name: PULSAR_ADVERTISED_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZK_SERVERS
          value: "kube-worker-1:2181,kube-worker-2:2181,kube-worker-3:2181"
        - name: ZK_CHROOT
          value: "pulsar"
        volumeMounts:
        - name: broker-logs
          mountPath: "/pulsar/logs"
        ports:
        - name: broker-service
          containerPort: 6650
          hostPort: 6650
        - name: web-server
          containerPort: 6680
          hostPort: 6680
