apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  namespace: diffraflow
  labels:
    name: docker-registry
spec:
  containers:
    - name: docker-registry
      image: registry:2
      ports:
        - containerPort: 443
          hostPort: 25443
      env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:443
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/cu01.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/cu01.key
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
      volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        - name: data
          mountPath: /var/lib/registry
  nodeSelector:
    kubernetes.io/hostname: kube-master-0
  tolerations:
    - operator: Exists
      effect: NoSchedule
  volumes:
    - name: certs
      hostPath:
        path: /kubernetes/registry/certs
    - name: data
      hostPath:
        path: /kubernetes/registry/data
  restartPolicy: Always
