apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zookeeper
  namespace: diffraflow
  labels:
    k8s-app: zookeeper
spec:
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      nodeSelector:
        diffraflow/zookeeper: present
      volumes:
      - name: zookeeper-data
        hostPath:
          path: "/data/zookeeper/data"
      - name: zookeeper-data-log
        hostPath:
          path: "/data/zookeeper/dataLog"
      - name: zookeeper-logs
        hostPath:
          path: "/data/zookeeper/logs"
      securityContext:
        runAsUser: 42700
        runAsGroup: 42700
        fsGroup: 42700
      containers:
      - name: zookeeper
        image: zhenghengli/zookeeper:3.5.7
        imagePullPolicy: Always
        args:
        - zkServer.sh
        - start-foreground
        env:
        - name: ZOO_STANDALONE_ENABLED
          value: "false"
        - name: ZOO_SERVERS
          value: >-
            server.1=kube-worker-1:2888:3888;2181
            server.2=kube-worker-2:2888:3888;2181
            server.3=kube-worker-3:2888:3888;2181
        volumeMounts:
        - name: zookeeper-data
          mountPath: "/zookeeper/data"
        - name: zookeeper-data-log
          mountPath: "/zookeeper/datalog"
        - name: zookeeper-logs
          mountPath: "/zookeeper/logs"
        ports:
        - name: client
          containerPort: 2181
          hostPort: 2181
        - name: server
          containerPort: 2888
          hostPort: 2888
        - name: leader-election
          containerPort: 3888
          hostPort: 3888
        - name: admin-server
          containerPort: 2180
          hostPort: 2180
