apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-config-{{ .Values.nameSuffix }}
  namespace: diffraflow
data:
  monitor.conf: |
    monitor_id = {{ .Values.monitorID }}
    image_http_host = 0.0.0.0
    image_http_port = {{ .Values.imageHttpPort }}
    request_timeout = 2000

    ## metrics http server
    metrics_http_host = 0.0.0.0
    metrics_http_port = {{ .Values.metricsHttpPort }}

    ## metrics pulsar setting
    # metrics_pulsar_broker_address = pulsar://pulsar-broker:6650
    # metrics_pulsar_topic_name = persistent://zhenghengli/diffraflow/monitor
    # metrics_pulsar_message_key = monitor-{{ .Values.nameSuffix }}
    # metrics_pulsar_report_period = 1000

  ingester_addresses.txt: {{ .Values.ingesterAddresses | quote }}
  log4cxx.properties: |
    log4j.rootLogger = DEBUG, Console
    log4j.appender.Console = org.apache.log4j.ConsoleAppender
    log4j.appender.Console.layout = org.apache.log4j.PatternLayout
    log4j.appender.Console.layout.ConversionPattern= %d [%t] %-5p %c - %m%n

